schedule:
  delay: 3000

# 템플릿에서 활용하는 프로퍼티
kafka:
  bootstrapAddress: localhost:9092
  topic:
    pubsub: test-pubsub
    reqrep:
      request: test-reqrep-request
      reply: test-reqrep-reply

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          destination: test-pubsub
          content-type: application/json
          group: foo2